//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiggle.Service.Test.ProductServiceHost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceHost.IProductServiceContract")]
    public interface IProductServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServiceContract/GetProducts", ReplyAction="http://tempuri.org/IProductServiceContract/GetProductsResponse")]
        Wiggle.Service.Models.Products.Results.GetProductsResult GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServiceContract/GetProducts", ReplyAction="http://tempuri.org/IProductServiceContract/GetProductsResponse")]
        System.Threading.Tasks.Task<Wiggle.Service.Models.Products.Results.GetProductsResult> GetProductsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceContractChannel : Wiggle.Service.Test.ProductServiceHost.IProductServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceContractClient : System.ServiceModel.ClientBase<Wiggle.Service.Test.ProductServiceHost.IProductServiceContract>, Wiggle.Service.Test.ProductServiceHost.IProductServiceContract {
        
        public ProductServiceContractClient() {
        }
        
        public ProductServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wiggle.Service.Models.Products.Results.GetProductsResult GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<Wiggle.Service.Models.Products.Results.GetProductsResult> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
    }
}
