//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiggle.Client.Test.ShoppingBasketService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingBasketService.IShoppingBasketServiceContract")]
    public interface IShoppingBasketServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingBasketServiceContract/CalculateBasketTotal", ReplyAction="http://tempuri.org/IShoppingBasketServiceContract/CalculateBasketTotalResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Backbone.Services.Results.GenericServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.Common.BaseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.ShoppingBasket.Result.CalculateBasketTotalResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.Products.GiftVoucherDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.Products.GiftVoucherDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.Products.OfferVoucherDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.Products.OfferVoucherType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.Products.ProductCategoryEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.Products.ProductDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wiggle.Service.Models.Products.ProductDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Wiggle.Service.Models.ShoppingBasket.Result.CalculateBasketTotalResult CalculateBasketTotal(Wiggle.Service.Models.ShoppingBasket.Request.CalculateBasketTotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingBasketServiceContract/CalculateBasketTotal", ReplyAction="http://tempuri.org/IShoppingBasketServiceContract/CalculateBasketTotalResponse")]
        System.Threading.Tasks.Task<Wiggle.Service.Models.ShoppingBasket.Result.CalculateBasketTotalResult> CalculateBasketTotalAsync(Wiggle.Service.Models.ShoppingBasket.Request.CalculateBasketTotalRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingBasketServiceContractChannel : Wiggle.Client.Test.ShoppingBasketService.IShoppingBasketServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingBasketServiceContractClient : System.ServiceModel.ClientBase<Wiggle.Client.Test.ShoppingBasketService.IShoppingBasketServiceContract>, Wiggle.Client.Test.ShoppingBasketService.IShoppingBasketServiceContract {
        
        public ShoppingBasketServiceContractClient() {
        }
        
        public ShoppingBasketServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingBasketServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingBasketServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingBasketServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wiggle.Service.Models.ShoppingBasket.Result.CalculateBasketTotalResult CalculateBasketTotal(Wiggle.Service.Models.ShoppingBasket.Request.CalculateBasketTotalRequest request) {
            return base.Channel.CalculateBasketTotal(request);
        }
        
        public System.Threading.Tasks.Task<Wiggle.Service.Models.ShoppingBasket.Result.CalculateBasketTotalResult> CalculateBasketTotalAsync(Wiggle.Service.Models.ShoppingBasket.Request.CalculateBasketTotalRequest request) {
            return base.Channel.CalculateBasketTotalAsync(request);
        }
    }
}
